import random
import uuid
from faker import Faker
from src.domain.entities import Order

fake = Faker()

class OrderFactory:
    """
    Generates random data for testing.
    Can produce Domain Entities (for Unit Tests) or Dictionaries (for API Tests).
    """

    @staticmethod
    def _base_data(**kwargs):
        """Internal method to generate raw random values."""
        return {
            "order_id": str(uuid.uuid4()),
            "symbol": random.choice(["BTC", "ETH", "SOL", "XRP"]),
            "quantity": round(random.uniform(0.1, 10.0), 4),
            "price": round(random.uniform(1000.0, 60000.0), 2),
            "side": random.choice(["BUY", "SELL"]),
            "metadata": {"source": "test_factory", "random_tag": fake.word()},
            **kwargs # Allow overriding specific fields
        }

    @classmethod
    def build_entity(cls, **kwargs) -> Order:
        """Returns a Domain Object (with __slots__)"""
        data = cls._base_data(**kwargs)
        # We don't send 'status' because __init__ sets it automatically
        return Order(
            order_id=data["order_id"],
            symbol=data["symbol"],
            quantity=data["quantity"],
            price=data["price"],
            side=data["side"],
            metadata=data["metadata"]
        )

    @classmethod
    def build_api_payload(cls, **kwargs) -> dict:
        """Returns a JSON-compatible dictionary for API requests"""
        data = cls._base_data(**kwargs)
        # API input doesn't need order_id (generated by backend)
        del data["order_id"]
        return data